# Generated by Django 5.2.13 on 2026-04-18 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_employer', 'Nuevo Empleador'), ('new_employee', 'Nuevo Empleado'), ('advance_request', 'Solicitud de Adelanto'), ('advance_approved', 'Adelanto Aprobado'), ('disbursement', 'Desembolso'), ('recovery', 'Recuperación'), ('system_alert', 'Alerta de Sistema')], max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Datos adicionales')),
                ('is_read', models.BooleanField(default=False, verbose_name='¿Leída?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación del Sistema',
                'verbose_name_plural': 'Notificaciones del Sistema',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error')], default='info', max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Enlace')),
                ('is_read', models.BooleanField(default=False, verbose_name='¿Leída?')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='advances.advance', verbose_name='Adelanto relacionado')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
