# Generated by Django 5.2.13 on 2026-04-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto solicitado')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Comisión')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('disbursed', 'Desembolsado'), ('recovered', 'Recuperado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo de la solicitud')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('disbursed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de desembolso')),
                ('recovery_date', models.DateField(blank=True, null=True, verbose_name='Fecha de recuperación (día de nómina)')),
                ('disbursement_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia de desembolso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adelanto',
                'verbose_name_plural': 'Adelantos',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(blank=True, max_length=20, verbose_name='Estado anterior')),
                ('status_to', models.CharField(max_length=20, verbose_name='Estado nuevo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Adelanto',
                'verbose_name_plural': 'Historial de Adelantos',
                'ordering': ['-created_at'],
            },
        ),
    ]
