# Generated by Django 5.2.13 on 2026-04-18 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advances', '0001_initial'),
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advances', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='advance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='advance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='users.employeeprofile', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='advancehistory',
            name='advance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='advances.advance', verbose_name='Adelanto'),
        ),
        migrations.AddField(
            model_name='advancehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por'),
        ),
    ]
