# Generated by Django 5.2.13 on 2026-04-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Razón social')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='NIT/RUC')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('max_advance_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Porcentaje máximo de adelanto (%)')),
                ('advance_fee_percentage', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='Porcentaje de comisión (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('is_verified', models.BooleanField(default=False, verbose_name='¿Verificada?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_day', models.PositiveSmallIntegerField(default=15, help_text='Día del mes en que se realiza el pago de nómina', verbose_name='Día de pago')),
                ('notify_on_advance_request', models.BooleanField(default=True, verbose_name='Notificar solicitudes de adelanto')),
                ('notify_on_advance_approved', models.BooleanField(default=True, verbose_name='Notificar aprobaciones')),
                ('min_advance_amount', models.DecimalField(decimal_places=2, default=50000, max_digits=12, verbose_name='Monto mínimo de adelanto')),
                ('max_advance_amount', models.DecimalField(decimal_places=2, default=1000000, max_digits=12, verbose_name='Monto máximo de adelanto')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresas',
            },
        ),
    ]
