# Generated by Django 5.2.14 on 2026-05-15 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superuser_profile', to=settings.AUTH_USER_MODEL, verbose_name='Superusuario')),
            ],
            options={
                'verbose_name': 'Perfil de Superusuario',
                'verbose_name_plural': 'Perfiles de Superusuarios',
            },
        ),
    ]
